name: CI + Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: run actual tests
        run: npx jest --testPathPattern="tests/actual" || true

      - name: run expected tests and generate coverage
        run: npx jest --coverage --testPathPattern="tests/expected"

      - name: Copy coverage report
        run: cp coverage/lcov.info /tmp/lcov.info || true

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: /tmp/lcov.info
          flag-name: run-${{ github.run_id }}



